### ISSUE TITLE
kube-dns-v20 Number of replicas too low (1) for multi-node cluster availability.

### ISSUE THREAD

**Issue by jeremyd** [coreos/kube-aws#111]
The number of replicas for kube-dns-v20 is set by default to 1 when setting up a new cluster.  This means that during a rolling-upgrade this service will go down multiple times while it gets re-scheduled to different nodes.  Upping the default replica count to 2, or 3 would be a better solution for people un-aware of this setting.  I'm hoping that the next time I spin up a cluster I won't have to remember to do this manually.  (config option or default > 1).

**Comment by mumoshu** [comment]
Hi @jeremyd, thanks for your feedback 👍 

In the meantime, I believe we should set at least 2 replicas for kube-dns by default.
I'd appreciate a pull request for that if you had some time :bow:

In the future, bundling cluster-proportional-autoscaler into kube-aws would be even nicer.
However cluster-proportional-autoscaler does not seem to support AWS yet.
So it will take some time until this nicer solution gets implemented.

Relevant upstream issue: https://github.com/kubernetes/kubernetes/issues/37567

**Comment by mumoshu** [comment]
This is now fixed in #178. Thanks for the feedback @jeremyd!
