### ISSUE TITLE
Kube-aws update

### ISSUE THREAD

**Issue by cisnky** [coreos/kube-aws#136]
Error: unknown command "update" for "kube-aws"

https://github.com/coreos/kube-aws/blob/master/Documentation/kube-aws-cluster-updates.md

Trying to increase the worker total without having to recreate the whole cluster.

**Comment by mumoshu** [comment]
Hi @cisnky, thanks for trying kube-aws!

What version of kube-aws are you using?
Would you mind trying the latest version which can be downloaded from https://github.com/coreos/kube-aws/releases ?

**Comment by cisnky** [comment]
No @mumoshu, Thank you for kube-aws, it's amazing!!

Currently using 0.8.3 via brew.

**Comment by cisnky** [comment]
All good.
