### ISSUE TITLE
What's the smallest instance size I can use?

### ISSUE THREAD

**Issue by cisnky** [coreos/kube-aws#138]
With 0.8.3 I could use t2.micro for the controller and the worker.

On 0.9.1 after setting up the cluster, I can't connect if using t2.micro.

**Comment by cisnky** [comment]
Worked my way up till it worked with t2.medium.

**Comment by pieterlange** [comment]
t2.micro (with 1GB memory) is pushing it for the controller server. On my cluster(s) the kube components peak above 1GB. I would also advise against using the T2 instance type for the controller if you're running anything serious.

Also note that `kube-aws` comes with a bunch of components by default: heapster and dashboard use some memory and CPU as well.

**Comment by mandrean** [comment]
From my company's real-world experiences, I'd say bare minimum for production is 1x m3.medium for both controller and etcd. But preferably at least 3x m3.medium for HA.

Skip the t2s for controller/etcd in production. You're screwed when you run out of CPU credits. Only use them for worker nodes.

**Comment by jelis** [comment]
I got stuff working with on nanos with 0.8.2 .. I really wish smaller instances worked!

**Comment by mumoshu** [comment]
Thanks for bringing up and info everyone!
I'm closing this as it is now documented in #162.

**Comment by scribnar** [comment]
@mandrean What you mean you are screwed if CPU credits expire? The baseline performance is still available so the controller will continue to run albeit with slow performance. I understand thats not a recommended scenario however you comment sounds like that is very dangerous scenario. I may be missing something here. Can you please explain "you are screwed"? Thanks.
