### ISSUE TITLE
Temporary files generated during tests not git ignored

### ISSUE THREAD

**Issue by c-knowles** [coreos/kube-aws#156]
As per the change to .gitignore in https://github.com/coreos/kube-aws/pull/142, there are some temporary files generating during tests that go into `config/temp/`. At first that seems fine as they get removed after the tests complete but they are not git ignored so if viewing a git diff during a test run many other files appear. My solution was to just add to .gitignore, it's simple and ensures temp files are never committed by accident.

My exact use case is I'm using Atom to edit and some plugin is running tests when I save. Since I often do a final save just before going to check a git diff, that's when I noticed it.

**Comment by mumoshu** [comment]
@c-knowles Thanks for raising this 👍 
I'll look into this shortly.

**Comment by mumoshu** [comment]
@c-knowles Hey, firstly, I apologize for misunderstanding your issue.

> viewing a git diff during a test run many other files appear

Yes, this should be fixed by addition to `.gitignore` as you've kindly done so in your PR.
Definitely there's no other way to fix it.

**Comment by mumoshu** [comment]
@c-knowles It turns out I was too rushed. I could fix the issue by simply creating temporary directories out of the git workspace.

**Comment by c-knowles** [comment]
Great! Tested for my use case and definitely working now.
