### ISSUE TITLE
k8s v1.5.0 requires --anonymous-auth=false flag

### ISSUE THREAD

**Issue by c-knowles** [coreos/kube-aws#159]
From the k8s changelog:

```
** Important Security-related changes before upgrading

You MUST set --anonymous-auth=false flag on your kube-apiserver unless you are a developer
testing this feature and understand it. If you do not, you risk allowing unauthorized users 
to access your apiserver.

You MUST set --anonymous-auth=false flag on your federation apiserver unless you are a 
developer testing this feature and understand it. If you do not, you risk allowing unauthorized
users to access your federation apiserver.

You do not need to adjust this flag on Kubelet: there was no authorization for the Kubelet APIs
in 1.4.
```

I heard they may be changing this flag to false by default in 1.5.1 as it broke various projects.

**Comment by mumoshu** [comment]
Thanks for the info :bow:

If I understand correctly, setting it to `false` would break the whole or a part of apiserver access via the host local network using curl like we've been doing in `cloud-config-controller`:

* https://github.com/coreos/kube-aws/blob/master/config/templates/cloud-config-controller#L199
* https://github.com/coreos/kube-aws/blob/master/config/templates/cloud-config-controller#L217
* https://github.com/coreos/kube-aws/blob/master/config/templates/cloud-config-controller#L249
* https://github.com/coreos/kube-aws/blob/master/config/templates/cloud-config-controller#L291
* https://github.com/coreos/kube-aws/blob/master/config/templates/cloud-config-controller#L351-L366
* https://github.com/coreos/kube-aws/blob/master/config/templates/cloud-config-controller#L395

**Comment by c-knowles** [comment]
OK, should those be addressed?

**Comment by mumoshu** [comment]
@c-knowles Yes, I believe this should be addressed in two steps.

The first step should be just providing `--anonymous-auth=false` to make Kubernetes 1.5.0 work with kube-aws. It doesn't degrade the security, anyways.

The next step should be improving kube-aws work with `--anonymous-auth=true` for higher security, though.

**Comment by mumoshu** [comment]
1.5.1 is released. Wow 😮 
The step 1 I've mentioned in the above comment would be unnecessary now.

**Comment by aaronlevy** [comment]
FWIW, the insecure api (localhost:8080) is not affected by these flags - as it bypasses all authN/authZ checks anyway.

**Comment by mumoshu** [comment]
@aaronlevy Thanks for sharing your insight 👍
Upgrading to 1.5.1 + `--anonymous-auth=false` wouldn't be that hard then.
