### ISSUE TITLE
Destructive defaults on 'kube-aws render'

### ISSUE THREAD

**Issue by pieterlange** [coreos/kube-aws#16]
I just accidentially ran `kube-aws render` without specifying whether i wanted to render the credentials or stack templates. The default now renders both, even if credentials already exist, overwriting the old credentials in the process.

I feel this is dangerous. We probably want to add a --force option to the `kube-aws render credentials` command.

Command output:
```sh
$ ./kube-aws render
WARNING: 'kube-aws render' is deprecated. See 'kube-aws render --help' for usage
Generating TLS credentials...
-> Generating new TLS CA
-> Generating new TLS assets
Success! Stack rendered to stack-template.json.

Next steps:
1. (Optional) Validate your changes to cluster.yaml with "kube-aws validate"
2. (Optional) Further customize the cluster by modifying stack-template.json or files in ./userdata.
3. Start the cluster with "kube-aws up".
```

**Comment by mumoshu** [comment]
Failing fast instead of implicitly overwriting previously generated assets also match the current behavior around `kube-aws init`, which fails when `cluster.yaml` exists.
Indeed It would be great to add!
