### ISSUE TITLE
Validate the tarball's GPG signature (windows 10)

### ISSUE THREAD

**Issue by igor90007** [coreos/kube-aws#185]
you write:
"Validate the tarball's GPG signature:

PLATFORM=linux-amd64
# Or
PLATFORM=darwin-amd64

gpg2 --verify kube-aws-${PLATFORM}.tar.gz.sig kube-aws-${PLATFORM}.tar.gz
Extract the binary:

tar zxvf kube-aws-${PLATFORM}.tar.gz
Add kube-aws to your path:

mv ${PLATFORM}/kube-aws /usr/local/bin"

What should I do for windows system? Are you support windows 10?

**Comment by mumoshu** [comment]
@igor90007 Thanks for your interest on kube-aws! Unfortunately, we don't have release binaries targeted to Windows as of today.
