### ISSUE TITLE
kube-aws up error: the bucket is not in 'us-west-1' region

### ISSUE THREAD

**Issue by helinwang** [coreos/kube-aws#205]
`kube-aws up --s3-uri s3://xxxxx`
> Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: template upload failed: Template upload failed: BucketRegionError: incorrect region, the bucket is not in 'us-west-1' region
	status code: 301, request id: 04xxxxxxxx

The bucket is indeed created for `us-west-1` region using `aws s3api --region=us-west-1 create-bucket --bucket xxxxx`

If I check on S3 web console, it shows `Region:	US Standard`, I have no idea where my S3 bucket region actually is.

```
$ kube-aws version  
kube-aws version v0.9.1
```

**Comment by mumoshu** [comment]
@helinwang Thanks for trying kube-aws!

The way you've created the bucket doesn't seem to work (for now or for your case).
AFAIK, `US Standard` is a logical region connected to us-east-1 which spans between us-west and us-east, hence not equal to `us-west-1` anyways.

I'd recommend reading [this SO thread](http://stackoverflow.com/questions/21008726/is-the-s3-us-standard-region-the-same-as-us-east-1-in-ec2) for more information.

Also, could you try creating your bucket from AWS console and then re-run `kube-aws up` with the  new s3-uri pointing to the bucket actually in us-west-1?

**Comment by helinwang** [comment]
@mumoshu Thanks for replying!
Creating from aws console and select "Northern California" works. Seems a problem from `aws cli` side.

Now I get
> Error: Error creating cluster: stack creation failed: AlreadyExistsException: Stack [test-kube-aws] already exists
	status code: 400, request id: 2b113e5e-d3aa-11e6-80c3-3fd6e578f194

Should I create separate issue?

**Comment by helinwang** [comment]
Tried a different cluster name using `kube-aws init`, problem still exists

> $ kube-aws up --s3-uri s3://kube-xxx/
> Creating AWS resources. This should take around 5 minutes.
> Error: Error creating cluster: stack creation failed: AlreadyExistsException: Stack [test-kube-aws-31415] already exists
> 	status code: 400, request id:

**Comment by mumoshu** [comment]
@helinwang each cluster's name must be unique in your AWS account/region. The part of the error mesasge "`Stack [test-kube-aws-31415] already exists`" seems to indicate that you've tried to use the duplicate name. You probably tried to re-run `kube-aws up` without running `kube-aws destroy`?

**Comment by mumoshu** [comment]
@helinwang Thanks for your reply!

Two things:

* `kube-aws destroy` doesn't wait until the stack deletion actually complete. Try `kube-aws destroy` and then running something like `aws cloudformation wait stack-delete-complete --stack-name test-kube-aws-314159`.
* The error "`AccessDenied: User: arn:aws:iam::578585771206:user/paddle is not authorized to perform: cloudformation:DescribeStackEvents on resource: arn:aws:cloudformation:us-west-1:578585771206:stack/test-kube-aws-314159/*`" does seem to be originated from IAM. Fix policy to allow calling `DescribeStackEvents` on cfn stacks would fix that.

**Comment by mumoshu** [comment]
@helinwang I guess you need the trailing asterisk in the resources part like `test-kube-aws-314159/*` according to http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html#d0e3095

Also I'm not sure why you added `arn:aws:iam::578585771206:role/test-kube-aws-314159/"` to the `Resources`. Probably unnecessary?

**Comment by helinwang** [comment]
Thanks @mumoshu , seems github markdown ate the `*` previously.
My current policy is begin to work (every time error message tell me a different permission that is necessary, and I manually add that to my policy list. Here is my current policy.)
Again, Are there any documentation what kind of cloudformation policy `kube-aws` needs? 
>  {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Allow",
>             "Action": [
>                 "iam:CreateRole",
>                 "iam:PutRolePolicy"
>             ],
>             "Resource": "*"
>         },
>         {
>             "Sid": "Stmt1482205746000",
>             "Effect": "Allow",
>             "Action": [
>                 "cloudformation:CreateStack",
>                 "cloudformation:UpdateStack",
>                 "cloudformation:DeleteStack",
>                 "cloudformation:DescribeStacks",
>                 "cloudformation:DescribeStackResource",
>                 "cloudformation:GetTemplate",
>                 "cloudformation:DescribeStackEvents"
>             ],
>             "Resource": [
>                 "arn:aws:cloudformation:us-west-1:578585771206:stack/test-kube-aws-314159/\*"
>             ]
>         }
>     ]
> }

**Comment by helinwang** [comment]
thanks @mumoshu this problem is resolved after adding `cloudformation:DescribeStackEvents` to cloudformation policy and `IAMFullAccess` to IAM.

**Comment by mumoshu** [comment]
@helinwang Ah, I've missed one of your questions.
List of all the IAM permissions required by kube-aws is not explicitly defined as of today. Please see the issue #88 for more info and the progress on that area. I'd greatly appreciate your contribution there.

Anyways, good to hear that it worked for you!
