### ISSUE TITLE
kube-aws up fail with error: CREATE_FAILED AWS::EC2::Subnet Subnet0 Value (us-west-1c) for parameter availabilityZone is invalid.

### ISSUE THREAD

**Issue by helinwang** [coreos/kube-aws#206]
Sorry for bothering again, I got

> CREATE_FAILED AWS::CloudFormation::Stack test-kube-aws-314159 The following resource(s) failed to create: [RouteTable, IAMInstanceProfileWorker, Subnet0, SecurityGroupEtcd, IAMInstanceProfileController, IAMInstanceProfileEtcd, SecurityGroupWorker, SecurityGroupElbAPIServer, VPCGatewayAttachment].
> 
> CREATE_FAILED AWS::EC2::Subnet Subnet0 Value (us-west-1c) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-west-1a, us-west-1b.

When running `kube-aws up --s3-uri s3://kube-31415/prefix`, any idea?

Thanks!

**Comment by mumoshu** [comment]
@helinwang Hi again!

Try using not `us-west-1c` but `us-west-1a` and/or `us-west-1b`.

Supported AZs for an AWS region varies among AWS accounts; your AWS account doesn't seem to support `us-west-1c`.

**Comment by helinwang** [comment]
@mumoshu Thanks for replying!

I changed `--availability-zone=us-west-1c` to `--availability-zone=us-west-1a` now it seems to be working.
Please note that in tutorial it's saying `--availability-zone=us-west-1c`, which I think need to be modified.

**Comment by mumoshu** [comment]
@helinwang Good to hear it worked!
Yes, the doc should be fixed somehow. I'd appreciate your contribution there if possible 👍

**Comment by helinwang** [comment]
@mumoshu Thanks, please see PR: https://github.com/coreos/kube-aws/pull/210

**Comment by mumoshu** [comment]
@helinwang Thanks!

Please beware that supported AZs varies among AWS accounts though. 1a+1b does work for you but not for others. So you should document it to guide an user to choose AZs supported in the target region for his/her specific AWS account.

**Comment by helinwang** [comment]
@mumoshu I see, sorry that I did not totally understand the problem before. Are there any hint from aws side showing which AZ is supported in reader's account, or it's based on trail and error?

**Comment by mumoshu** [comment]
@helinwang AFAIK, `aws ec2 describe-availability-zones` shows supported AZs. Does it work for you too?
