### ISSUE TITLE
rkt too old in CoreOS stable

### ISSUE THREAD

**Issue by philips** [coreos/kube-aws#21]
Based on the report here kube-aws uses CoreOS Linux stable but Kubernetes doesn't like this old version of rkt: https://github.com/coreos/bugs/issues/1640

**Comment by mumoshu** [comment]
@philips Thank you for your information!

Anyways, kube-aws users won't be/wouldn't have been affected.

kube-aws is already aware of that and had been [failing fast](https://github.com/coreos/kube-aws/blob/master/config/config.go#L215-L218) when tried to use rkt with CoreOS stable older than [1151.0.0](https://coreos.com/releases/#1151.0.0), which implied rkt older than 1.13.0 (thanks to @pbx0 )

Let me also add that, starting today, it is ok to use rkt+stable, beucause the latest version of CoreOS stable [1185.3.0](https://coreos.com/releases/#1185.3.0), released today, is bundled with rkt 1.14.0.
