### ISSUE TITLE
Route53 error 

### ISSUE THREAD

**Issue by ttrahan** [coreos/kube-aws#211]
First attempt running through the Getting Started docs. I received the following error when attempting to have kube-aws automatically configure my A record in Route53.

```
Error: Error creating cluster: RecordSet for "example-kube-cluster.com" already exists in Hosted Zone "."
```

However, I don't have any A records configured for the Hosted Zone. 

![image](https://cloud.githubusercontent.com/assets/4467650/21737451/a34fc3c8-d42d-11e6-86df-e10235df75fb.png)

Any ideas?

**Comment by redbaron** [comment]
needs to be a host within a zone: `<something>.example-kube-cluster.com`

**Comment by ttrahan** [comment]
got it, thanks.
