### ISSUE TITLE
Confusion regarding kube-aws update in docs 

### ISSUE THREAD

**Issue by reiinakano** [coreos/kube-aws#212]
Hey, I'm a little confused regarding how I'm supposed to approach updating my cluster `using kube-aws update`. I've read the docs many times over to clear this up and this is my understanding so far. Every time I make changes to cluster.yaml only, there's no need to call `kube-aws render stack`. All I need to do is call `kube-aws update` immediately. And then if I make direct changes to template.json, I should call` kube-aws render stack`, `kube-aws render credentials`, then `kube-aws update`. 

Upon experimenting with cluster updates, it turns out that when I change the number of workers, instance types, etc in cluster.yaml, that's the time I need to call `kube-aws render stack` first to manually update template.json (otherwise I get cloudformation error). On the other hand, when I directly mess with template.json (to change iam role), I should NOT call` kube-aws render stack`, otherwise my manual changes will be overwritten in template.json. Am I missing something? If this is the intended behavior the docs seem very misleading. 

On a related note, how should I do stuff like modifying the iam role if template.json gets overwritten every time I call `kube-aws render stack` anyway? 

Thanks.

**Comment by redbaron** [comment]
we are using inhouse tool for that backed by git. Idea is to render only to "upstream" branch and then merge it into your branch where your changes to previously rendered template.json are. that way when you update kube-aws it will render new version of the cluster config, which can be neatly merged with your customizations.

Also I am not convinced that changing number of workers in cluster.yaml result in any change in rendered json files, what error do you see?

**Comment by reiinakano** [comment]
>  	04:12:32 UTC+0800 	UPDATE_ROLLBACK_IN_PROGRESS 	AWS::CloudFormation::Stack 	ae-cluster 	The following resource(s) failed to update: [AutoScaleController].
> 	04:12:31 UTC+0800 	UPDATE_FAILED 	AWS::AutoScaling::AutoScalingGroup 	AutoScaleController 	MinInstancesInService must be less than the autoscaling group's MaxSize
> 	04:12:28 UTC+0800 	UPDATE_IN_PROGRESS 	AWS::AutoScaling::AutoScalingGroup 	AutoScaleController 	
> 	04:12:23 UTC+0800 	UPDATE_COMPLETE 	AWS::AutoScaling::LaunchConfiguration 	LaunchConfigurationController 	
> 	04:12:23 UTC+0800 	UPDATE_COMPLETE 	AWS::AutoScaling::LaunchConfiguration 	LaunchConfigurationWorker 	
> 	04:12:23 UTC+0800 	UPDATE_IN_PROGRESS 	AWS::AutoScaling::LaunchConfiguration 	LaunchConfigurationController 	Resource creation Initiated
> 	04:12:23 UTC+0800 	UPDATE_IN_PROGRESS 	AWS::AutoScaling::LaunchConfiguration 	LaunchConfigurationWorker 	Resource creation Initiated
> 	04:12:22 UTC+0800 	UPDATE_IN_PROGRESS 	AWS::AutoScaling::LaunchConfiguration 	LaunchConfigurationController 	Requested update requires the creation of a new physical resource; hence creating one.
> 	04:12:22 UTC+0800 	UPDATE_IN_PROGRESS 	AWS::AutoScaling::LaunchConfiguration 	LaunchConfigurationWorker 	Requested update requires the creation of a new physical resource; hence creating one.
> 	04:12:12 UTC+0800 	UPDATE_IN_PROGRESS 	AWS::CloudFormation::Stack 	ae-cluster 	User Initiated

This is what happened when I attempted to change number of workers from 1 to 2 without rerendering json template

**Comment by redbaron** [comment]
Interesting, it complains that in your cluster.yaml  `controller.autoScalingGroup.maxSize` <= `controller.autoScalingGroup.rollingUpdateMinInstancesInService`, are you sure calling `kube-aws render` solves it somehow? Can you provide a diff of `stack-template.json` before and after render, please?

**Comment by c-knowles** [comment]
I may be able to help. Which kube-aws release are you using? When you changed the worker count, did you change `workerCount` or `worker.autoScalingGroup` or both in cluster.yaml?

**Comment by reiinakano** [comment]
Hi all, I was using V0.9.1 when I faced this issue. I've since updated to 0.9.3-rc.2 and have not faced this issue since. Although I did spend an entire day frustrated over #199 but that's a different story :)

Thanks everyone.

**Comment by c-knowles** [comment]
Great, glad a later version is working better for you.
