### ISSUE TITLE
taint-and-uncordon task continuously fails on controller nodes due to typo in taint

### ISSUE THREAD

**Issue by whereisaaron** [coreos/kube-aws#215]
kube-aws version v0.9.3-rc.2

I was surprised that the controllers created by kube-aws 0.9.3-rc.2 were neither cordoned nor tainted. Checking the controller I found the `taint-and-uncordon` task was repeatedly failing due to a typo in the taint.

The attempted taint is `node.alpha.kubernetes.io/role:master:NoSchedule`
but should be `node.alpha.kubernetes.io/role=master:NoSchedule`. This results in the error:

```
Jan 08 05:02:27 ip-1.1.1.1.region.compute.internal taint-and-uncordon[9184]: [  579.594914] hyperkube[5]: error: at least one taint update is required
```

A second problem with this task, is that even though the taint attempt fails and returns an error, the task does not check for errors/success and goes ahead an uncordons the controller anyway. Since the controller is now untainted and uncordoned it starts being scheduled for regular/user pods.

```
run --volume=kube,kind=host,source=/etc/kubernetes,readOnly=true --mount=volume=kube,target=/etc/kubernetes --uuid-file-save=/var/run/coreos/taint-and-uncordon.uuid --volume=dns,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=dns,target=/etc/resolv.conf --net=host --trust-keys-from-https quay.io/coreos/hyperkube:v1.5.1_coreos.0 --exec=/bin/bash -- -vxc echo tainting this node; \
                                                                                    hostname="ip-172-23-146-158.ap-southeast-2.compute.internal"; \
                                                                                    kubectl="/kubectl --server=http://127.0.0.1:8080"; \
                                                                                    taint="$kubectl taint node $hostname"; \
                                                                                    $taint "node.alpha.kubernetes.io/role:master:NoSchedule"; \
                                                                                    echo done. ;\
                                                                                    echo uncordoning this node; \
                                                                                    $kubectl uncordon $hostname;\
                                                                                    echo done.
```

**Comment by whereisaaron** [comment]
I manually tainted the node but that doesn't help because the task doesn't check if the taint is already there or `--overwrite` it.

Over time I get more and more of these 'No such container' messages building up on the controller. About every 60 seconds there is a whole bunch of them dumped in the log.

```
Jan 08 05:18:51 ip-1.1.1.1.region.compute.internal dockerd[1570]: time="2017-01-08T05:18:51.716234800Z" level=error msg="Handler for GET /containers/46e6f5c6902c0372223728cea2870091953dac222aaba27a729af484aeab784f/json returned error: No such container: 46e6f5c6902c0372223728cea2870091953dac222aaba27a729af484aeab784f
````

Seems like the failed rkt task doesn't get cleaned up properly? The constant failure keep the controller CPU load high and it trends slower higher over time until other things start failing on the controller and it snowballs.

This 'taint-and-uncordon' task is a bit of a menace, could it be moved to an experimental feature until it has a version with more checking / error handling?

**Comment by whereisaaron** [comment]
I patched `taint-and-uncordon` so it has error checking and the typo is fixed. Now it runs, but it immediately causes other problems. It taints that node with a taint that none of services on the controller tolerate. This means that if the `taint-and-uncordon` runs before all or some of the services have been scheduled, they get stuck in 'Pending' state because there is no valid node to schedule them on.

Tainting the node is a good idea, but I think it only makes sense if all the controller manifests include toleration for that taint. That is how tainting is supposed to work I think? My new controller looks like below, with most services stuck 'Pending' (it has zero workers nodes because using node pools). The taint has thrown a spanner in the works so the services will not function until the taint is removed.

```
NAMESPACE     NAME                                                                        READY     STATUS    RESTARTS   AGE
kube-system   heapster-v1.2.0-3646253287-rb07b                                            0/2       Pending   0          20m
kube-system   kube-apiserver-ip-11-111-111-111.ap-southeast-2.compute.internal            1/1       Running   0          19m
kube-system   kube-controller-manager-ip-11-111-111-111.ap-southeast-2.compute.internal   1/1       Running   0          20m
kube-system   kube-dns-782804071-zgbpb                                                    0/4       Pending   0          20m
kube-system   kube-dns-autoscaler-2813114833-qmdb0                                        0/1       Pending   0          20m
kube-system   kube-proxy-ip-11-111-111-111.ap-southeast-2.compute.internal                1/1       Running   0          19m
kube-system   kube-scheduler-ip-11-111-111-111.ap-southeast-2.compute.internal            1/1       Running   0          19m
kube-system   kubernetes-dashboard-v1.5.0-j1kpv                                           0/1       Pending   0          20m
```

This always happens if you enable RBAC, because until you load some base permissions for the default Service Account these services won't start. But by that time the node is already tainted with a taint that the controller services don't tolerate, so they can't start.

I'm patching out `taint-and-uncordon` entirely for now. When all the controller services are updated to tolerate the taint, then we can added it back in.

**Comment by whereisaaron** [comment]
I may have the wrong end of the stick, this discussion from the k8s website says those pods I had stuck pending never should run on a master. It that still the case, or is the from the older situation when masters were not fully-fledged work nodes?

http://kubernetes.io/docs/admin/rescheduler/
"In addition to Kubernetes core components like api-server, scheduler, controller-manager running on a master machine there are a number of add-ons which, for various reasons, must run on a regular cluster node (rather than the Kubernetes master). Some of these add-ons are critical to a fully functional cluster, such as Heapster, DNS, and UI."

**Comment by mumoshu** [comment]
@whereisaaron Hi, thanks for bringing this up!

Regarding how taint-and-uncordon should be fixed, I've left a comment in https://github.com/coreos/kube-aws/pull/199. Let's keep discussing there!

Could you confirm that the exact list of components stuck pending are kube-dns, kube-dashboard and heapster?
If that's the case, yes; those components are intended to be run in worker nodes before/after the taint-and-uncordon thing.
However I'm open to suggestion(s) to make them configurable regarding which kind of nodes to be scheduled if necessary.

**Comment by whereisaaron** [comment]
Thanks for confirming @mumoshu. Yes those were the Pending components. I think the current situation is reasonable, so long as the api server and controller components can get by without kube-dns?

So probably no need to make configurable unless you wanted to support a single-node minikube-style situation; I don't personally have that use case.

**Comment by mumoshu** [comment]
Thanks as always @whereisaaron!
AFAIK yes; apiserver and controller-manager don't depend on those cluster addons.
Anyways I'm closing this as the original issue has already been resolved but feel free to reopen if necessary.
