### ISSUE TITLE
`cloud-config-etcd` is incompatible with CoreOS >=1284.0.0

### ISSUE THREAD

**Issue by redbaron** [coreos/kube-aws#218]
Recently released 1284.0.0 removed `early-docker.service` unit file which is used by `decrypt-tls-assets` script

**Comment by mumoshu** [comment]
@redbaron Thanks for the info 👍

If I remember correctly, only the `cloud-config-etcd` is relying on the `decrypt-tls-assets.service` which depends on `early-docker.service` and therefore fixing `cloud-config-etcd` to include `/opt/bin/decrypt-tls-assets` in an `ExecStartPre` part of systemd units would resolve this issue.

FYI, here is [the relevant part of cloud-config-controller](https://github.com/coreos/kube-aws/blob/master/config/templates/cloud-config-controller#L61)

**Comment by redbaron** [comment]
With #226 merged it is all fine now
