### ISSUE TITLE
Error: unknown flag: --generate-ca

### ISSUE THREAD

**Issue by tnguyen14** [coreos/kube-aws#229]
Trying to follow the documentation for the `render credentials` step, but I got the following error:

```shell
:; kube-aws render credentials --generate-ca
Error: unknown flag: --generate-ca
```

I am on `kube-aws` version 0.8.3. Help doesn't show me what the flags are:

```shell
:; kube-aws render --help
Render a CloudFormation template

Usage:
  kube-aws render [flags]
```

I'm not sure if I am doing something incorrectly.

**Comment by redbaron** [comment]
use latest v0.9.3-rc.2

**Comment by tnguyen14** [comment]
when will it be generally available?

I was just doing `kube-aws render` before, and I see the files `ca.pem` and `ca-key.pem` generated in `credentials`. Is that the same?

**Comment by mumoshu** [comment]
Yes, that's the same!
kube-aws is very busy focusing on implementing the most requested features and fixes and merging PRs and unfortunately every release doesn't have a clear estimated release date.
But v0.9.3 is already tagged and even v0.9.4-rc.1 is already released.

**Comment by mumoshu** [comment]
Closing this as the original question is already answered but please feel free to reopen if necessary.
