### ISSUE TITLE
`kube-aws update` fails when updating credentials

### ISSUE THREAD

**Issue by drywheat** [coreos/kube-aws#237]
### Library versions

platform: **MacOS 10.12.1**
kube-aws: **v0.9.3-rc.2**
awscli: **aws-cli/1.11.36 Python/2.7.10 Darwin/16.1.0 botocore/1.4.93**

### Synopsis

I was able to render my credentials, stack and stand up a k8s cluster using `kube-aws` and the online docs for guidance. After my new stack was operational I realized that I configured my **externalDNSName** name incorrectly and needed to correct it. My attempts to update my new cluster have failed with very little context given in the error messages.

### Steps taken

1. I corrected the value of the **externalDNSName** attribute inside of `cluster.yaml`.
2. I rendered new credentials using `kube-aws render credentials`.
3. I executed the update command like so: `kube-aws update --s3-uri s3://my/own/path`.

This command errors out with the following message:

```bash
$ kube-aws update --s3-uri s3://bucket-name/
Error: Error updating cluster: error updating cloudformation stack: stack update failed: ValidationError: No updates are to be performed.
        status code: 400, request id: c643fab7-d817-11e6-836e-7b3d1e23ea7e
```

Has anyone else seen this behavior? It looks like some type of validation error obviously, but the message isn't very clear about what is invalid inside of the stack definition. I wasn't able to find an issue (open/closed) that mentioned this outcome.

**Comment by redbaron** [comment]
Looks like you didn't set `createRecordSet: true`

**Comment by drywheat** [comment]
I have `createRecordSet: true` inside of my cluster.yaml file and I've verified that it DOES create the ELB alias record inside of my Route53 hosted zone.

Why did you suspect that it was not set?

**Comment by redbaron** [comment]
well, because CF things there is nothing to do and Route53 entry is conditionally included based on `createRecordSet` value.

OK I re-read your initial message, you mentioned `kube-aws render credentials`, but did you do `kube-aws render stack` after updating cluster.yml? try running it.

Also try to use most recent RC, important changes were added there

**Comment by drywheat** [comment]
I initially tried w/o rendering the stack but, after that failed, I then proceeded to render the stack and try again. I even uploaded my `stack-template.json` file to my s3 bucket after performing all of these rendering actions. It failed in the exact same way after each step.

I wasn't aware that a new RC was released yesterday. I'll download that binary and try to replicate the error again, this time collecting debug logs from AWS.

**Comment by redbaron** [comment]
If new version still doesn't work, do a diff between `kube-aws render stack --export --pretty-print` output before and after update of `cluster.yml`, it should show changes in `ExternalDNS` CF section.

**Comment by danielfm** [comment]
Another valid use case is that eventually we'd want to rotate the certificates, without changing the `externalDNSName`. Today, if we just run `kube-aws render credentials` and then `kube-aws update`, as instructed by the [documentation](https://github.com/coreos/kube-aws/blob/master/Documentation/kube-aws-cluster-updates.md), the same error occurs:

```
Error: Error updating cluster: error updating cloudformation stack: stack update failed: ValidationError: No updates are to be performed.
	status code: 400, request id: ...
```

**Comment by redbaron** [comment]
@danielfm do you still see it if you delete all `credentials/*.enc` and run update?

**Comment by danielfm** [comment]
@redbaron Hmm, didn't try that.. one test I'm performing right now was to add a comment to both `cloud-config-controller` and `cloud-config-worker` files, and the update is rolling as we speak. Let me see if this works and I'll test your suggestion as well.

**Comment by drywheat** [comment]
Just so that we're all on the same page @danielfm, can you verify that you're using kube-aws **v0.9.3-rc.2**?

**Comment by danielfm** [comment]
@drywheat `kube-aws version v0.9.3-rc.3`

**Comment by mumoshu** [comment]
@danielfm @redbaron I've updated the doc https://github.com/coreos/kube-aws/commit/4cefe4714effa79495709d9a63c3d31e7b86c22c
Thanks for your support and the info!

**Comment by drywheat** [comment]
Thanks y'all.
