### ISSUE TITLE
Creating cluster without having a domain name

### ISSUE THREAD

**Issue by helinwang** [coreos/kube-aws#244]
After following the full tutorial, my understanding is that one must own a domain name to create a kubernetes cluster on AWS.
E.g., need a domain name for parameter `--external-dns-name` in `kube-aws init`.

Considering not everyone owns a domain. Are there any option for one to create a cluster without domain name? (E.g., access the cluster by ip, not by domain name)

**Comment by mumoshu** [comment]
@helinwang Thanks for the feedback!

It definitely seems like an issue I'd like to fix but several things to be considered:

* Does modifying your `/etc/hosts` to point to public IPs of your controller ELB load balancer work? I believe running `dig <elb endpoint>` after `kube-aws up` reveals actual public IPs of your ELB.
* An ELB is required (at least in kube-aws) in front of controller nodes serving e.g. k8s api via external dns name. Also note that an ELB can't be assigned static IPs.

**Comment by redbaron** [comment]
@helinwang if you use existing VPC,  you can create ELB yourself and then use it's domain name as `externalDnsName`. You'd then need to modify `stack-template.json` and set value of `LoadBalancerNames`  under `AutoScaleController` resource:

```
        "LoadBalancerNames" : [ "YOUR-ELB-NAME" ]
```

You'll also need to create your apiserver certificate which lists that domain.

@mumoshu , In *theory* kube-aws could have mini CF `stack-bootstrap.json`  where it creates everything it needs to know for main `cluster up` in advance: kms key, s3 bucket for rest of stacks, controllers ELB to obtain static name. It then fills defaults using them.

**Comment by iameli** [comment]
There are plenty of free subdomain services out there too -- [here's one](http://www.homenet.org/). That'd work just fine for the external DNS requirement.

**Comment by mumoshu** [comment]
@redbaron 

> In *theory* kube-aws could have mini CF `stack-bootstrap.json`  where it creates everything it needs to know for main `cluster up` in advance: kms key, s3 bucket for rest of stacks, controllers ELB to obtain static name. It then fills defaults using them.

Ah, it could be possible!
If we care that way, I'm not opposed to add a doc to do that around kube-aws with minimum addition to kube-aws itself(maybe accepting the name of existing ELB instead of `externalDnsName` in cluster.yaml?)`.

**Comment by mumoshu** [comment]
Hi @helinwang, does any of the solutions solve your issue? 😃

**Comment by helinwang** [comment]
Thanks everyone for the input! I ended up using the modify `/etc/hosts` solution. @mumoshu yes it's resolved! Thanks!

**Comment by helinwang** [comment]
@mumoshu Just want to give feedback on the `/etc/hosts` solution, it does not work unless the `/etc/hosts` files are edited in the ec2 machines as well. Since they need domain to connect.
Did not have time to try other solutions yet.

**Comment by mumoshu** [comment]
@helinwang Thanks for the feedback! I'd appreciate it if you could share results for other possible solutions :bow:

**Comment by helinwang** [comment]
@mumoshu We ended up changing local /etc/hosts and amazon DNS: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/k8s/k8s_aws_en.md#add-route53-private-name-service-in-vpc

**Comment by adrinjalali** [comment]
For future reference, I tested the solution using [this](http://www.homenet.org/) provider, and [these instructions](https://github.com/kubernetes/kops/blob/master/docs/aws.md#scenario-3-subdomain-for-clusters-in-route53-leaving-the-domain-at-another-registrar), and it worked. I had to create an `NS` record, with one of the nameservers returned by amazon. Probably not very reliable, but it works.

**Comment by mumoshu** [comment]
Thanks for your efforts @helinwang and @adrinjalali :bow: 👍

**Comment by arturgaleno** [comment]
As @helinwang link said, creating a Privated Hosted Zone, then a Record Set pointing to controller ip, and editing my local machine /etc/hosts really works.
