### ISSUE TITLE
Emit a warning message when `t2.nano` or `t2.micro` is set for `*instanceType`

### ISSUE THREAD

**Issue by mumoshu** [coreos/kube-aws#258]
Regardless of the fact that `t2.medium` being the minimum default instance type in kube-aws these days, I believe some people are still trying to use `t2.micro` for nodes by modifying `cluster.yaml` and resulting their clusters to not functional.

I've recently received a question in the k8s slack about why `kube-aws up` didn't create a working cluster and one of the causes was `t2.micro`.
I'm going to add validation to forbid using `t2.micro` to stop trapping new-comers and to reduce the amount of support required to learn k8s via using kube-aws.

I'll leave this open for a while to hear from the community before I actually add the validation.

Also see #138 and #184

**Comment by valichek** [comment]
I think I would be enough to have some warning in `cluster.yaml`. And maybe some description of possible issues.

**Comment by mumoshu** [comment]
Thanks for the comment @valichek!
AFAIK, using `t2.micro` almost consistently result in non-functional nodes.
So it isn't an "possible" issue but almost a persistent issue.
Just curious but are you still wanting to try `t2.micro`?

**Comment by valichek** [comment]
@mumoshu I'm running minimal cluster using `t2.micro` for controller/etcd nodes and `t2.nano` for workers and it's cheaper. I don't have any issues on startup (`0.9.1`). We use it as test/learning dev environment and don't run heavy jobs, so we still don't have such issues. And of course, we do understand that we cannot use it for serious tasks.

**Comment by mumoshu** [comment]
@valichek I'm surprised it is working for you! Thanks for the info.
As I'm not intended to break existing use-case as long as it is working, I'll just add warnings to somewhere then.

**Comment by mumoshu** [comment]
Btw warnings already exist in `cluster.yaml` as of today
https://github.com/coreos/kube-aws/blob/master/config/templates/cluster.yaml#L75
Probably I need to add louder warnings somewhere?
