### ISSUE TITLE
Wait until apiserver becomes ready to serve API before `kube-aws up` finishes

### ISSUE THREAD

**Issue by mumoshu** [coreos/kube-aws#259]
kube-aws as of today prints the message `You should be able to access the Kubernetes API once the containers finish downloading.` after `kube-aws up` completes.
This message expresses that an user must hold on for a few minutes until the apiserver becomes ready to serve API i.e. `kubectl` succeeds.

I've recently received a question in the k8s slack about why `kube-aws up` didn't create a working cluster and one of the gotcha for the one was `kubectl` doesn't succeed immediately after `kube-aws up` completes which is IMHO obvious if one is very careful. In other words, just printing a message like now isn't very friendly.

One of the ways to make it a bit more friendlier is to make `waitSignal` graduate from experimental so that a controller ASG waits until apiserver becomes responsive.

I'll leave this open for a while to hear from the community for ideas.

**Comment by redbaron** [comment]
`waitSignal` is the way to go. Conditions of firing need to be refined probably, such as check that apiserver is running.

As for the cluster readiness, what to do if no workers are set (nodepool only approach)? then there is no kube-dns running and cluster is non functional

**Comment by ankon** [comment]
Wait signals work nicely already, I was surprised to see them marked as experimental (and then couldn't find any documentation about any gotchas, plus the code looked sane -- so I enabled them.)

Indeed it would be nice to have the cluster be ready-to-use when the command returns.

**Comment by gianrubio** [comment]
If nobody is working on this I can do!

**Comment by c-knowles** [comment]
Is it worth considering a `--wait` flag to keep the current behaviour the default? Or do we always want to wait?

**Comment by gianrubio** [comment]
I propose to create a config --skip-wait for the best experience with new users. By default we always wait until the resources are creating. Advanced users can easily skip with this option.

**Comment by mumoshu** [comment]
@gianrubio 👍 to the `--skip-wait`

**Comment by mumoshu** [comment]
But please beware that there's currently no way to wait for nodes powered by a spot fleet!
I'd appreciate it if you could add a warning for users that it doesn't wait for spot fleets.

**Comment by gianrubio** [comment]
Got it @mumoshu, also it's time to remove waitSignal from experimental and get more feedback from users, can I do this in the same PR?

**Comment by mumoshu** [comment]
@gianrubio Please do so 👍

**Comment by gianrubio** [comment]
> But please beware that there's currently no way to wait for nodes powered by a spot fleet!
I'd appreciate it if you could add a warning for users that it doesn't wait for spot fleets.

@mumoshu could you explain why is not possible to wait signals from spoot fleets?

**Comment by mumoshu** [comment]
@gianrubio cfn-signal doesn't support spot fleets/SpotFleet resources in CloudFormation don't support signaling.
