### ISSUE TITLE
Don't precalculate etcd static IP addresses

### ISSUE THREAD

**Issue by sasso** [coreos/kube-aws#266]
@redbaron @mumoshu is there a way to do a zero downtime migration from previous state (before PR #226 was introduced)

**Comment by redbaron** [comment]
it shouldn't affect existing setups as new resources are "blacklisted" during update phase. only change is to userdata on workers and controllers, but it is updated regularly so normal procedure applies

**Comment by sasso** [comment]
![screenshot 2017-01-18 15 01 04](https://cloud.githubusercontent.com/assets/8398242/22086736/000158f6-dd8f-11e6-8c09-3929da6ae14a.png)

InstanceEtcd0eni... are unlinked so deployment will not work

**Comment by redbaron** [comment]
Thats fine,because userdata use 'InstanceEtcd0.PrivateIpAddress' which exists in both old and new deployments

**Comment by redbaron** [comment]
BTW, is  it unpublished patch you have or some manual work to create CF changesets?

**Comment by sasso** [comment]
I dumped the CF generated with update

**Comment by mumoshu** [comment]
@sasso Thanks as always for your interest on kube-aws!

Sorry for the long silence but answering your original question; no, there's no way to achieve zero-downtime migration from the previous state for now. The support for zero-downtime migrations for not all but at least significant paths is definitely a feature which we want to support in the future but is not very focused as of today. The main reason is that we don't have enough resources to design it.

To be clear, running `kube-aws update` between different kube-aws versions as of today may or may not result in a zero-downtime update. It's really up to what is actually updated and how, for your own case.

**Comment by mumoshu** [comment]
@sasso FYI, I tend to completely replace a kube-aws cluster in our prod env when I need the latest enhancements from kube-aws.

It would sound a bit hard to do in practice. However, to ease replacements, I'm using [helm](https://github.com/kubernetes/helm) to make our deployments very repeatable.

The procedure contains steps like:

* Create new a new kube-aws cluster and 
* Add all the worker nodes in the new cluster to be load-balanced by our public ELBs serving production workloads (e.g. via `experimental.loadBalancer.Names`)
* Deploy all the apps via `helm install` in sequence, and then
* Verify all new worker nodes are healthy and serving prod workloads
* If everything is working, switch the kubernetes api endpoint to where our CI points to the one for the new cluster, and then 
* If something looks broken, investigate and optionally recreate the helm releases and/or the kube-aws cluster and try again

I'd like to automate it even further in the future but it is working for me and our company anyways.

**Comment by mumoshu** [comment]
Closing this as the original question is answered but please feel free to reopen if necessary.
