### ISSUE TITLE
Quota error when creating instances (0.9.3-rc.5)

### ISSUE THREAD

**Issue by numair** [coreos/kube-aws#270]
Hi, just been playing with kube-aws on a clean AWS account.  I've been able to create an instance in my region and availability zone via AWS console, so I know that I don't have some sort of quota limit across my account; when I try to create a cluster using kube-aws, however, I get the following error:

```
Creating AWS resources. This should take around 5 minutes.
Error: Error creating cluster: Stack creation failed: CREATE_FAILED : The following resource(s) failed to create: [InstanceEtcd0]. 

Printing the most recent failed stack events:
CREATE_FAILED AWS::CloudFormation::Stack my-stack-2 The following resource(s) failed to create: [InstanceEtcd0].
CREATE_FAILED AWS::EC2::Instance InstanceEtcd0 Your quota allows for 0 more running instance(s). You requested at least 1
```

I'm using the master credentials from this AWS account, and aside from a test micro instance I've got nothing else going on in the account. The region and AZ for the kube-aws config is the same as the currently-running micro instance, so I assume it's not a quota issue for the region.  Am I doing something wrong?  I followed the tutorial pretty closely...  Thanks!

**Comment by redbaron** [comment]
this looks like an account limit, you need to raise AWS account support request

**Comment by numair** [comment]
@redbaron Weird... When I look at the quota limits for the account, there's the standard 20 instances. But I just tried to create an additional instance via the web console, and sure enough I encountered a quota error.  Since there's likely to be a lot of people experimenting with this project using a new AWS account (it sort of generates stuff all over the place), do you have any advice on best practices for this situation?

I've submitted a request for a quota increase, maybe that is a necessary "Step 1"?  It's been a while since I've created a new AWS account -- surprised that the default instance limit is basically 1 now.

**Comment by c-knowles** [comment]
@numair I've also been confused by a similar error before in one of two particular conditions - if billing details are not entered and if the account is not "verified" (means they SMS or automated-call you). In my case the account sign up process did not send me through this verification at all, not sure why! Maybe check [this page](https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/) if you've not done those steps.

**Comment by numair** [comment]
@c-knowles This was the reply I got from Amazon support (I have a Developer support contract):

"I understand that you are not able to launch new instances under your account. This is because you just joined AWS today and has been only less than 24 hours. Generally, it takes 24 hours after creation of an account to get the EC2 limit increased to 20. Please try again after some time."

Basically: if you are going to make an account to test kube-aws, you should wait 24 hours to begin playing around.
