### ISSUE TITLE
Using EFS with kube-aws

### ISSUE THREAD

**Issue by reiinakano** [coreos/kube-aws#273]
Hi, I've created a kube-aws cluster with this setting in cluster.yaml `elasticFileSystemId: fs-c590348c`

I am able to create a persistent volume through a Kubernetes config file (using type NFS and pointing to the DNS name of my EFS) and the corresponding persistent volume claim. However, I am unable to mount the PVC on my pod with this error:

> 
> Unable to mount volumes for pod "ae-redis-deployment-987559166-pvtcj_default(f3e38bc3-de2e-11e6-88bf-0a0cd9970f7c)": timeout expired waiting for volumes to attach/mount for pod "ae-redis-deployment-987559166-pvtcj"/"default". list of unattached/unmounted volumes=[redis-data]
> Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "ae-redis-deployment-987559166-pvtcj"/"default". list of unattached/unmounted volumes=[redis-data]  

Am I missing anything? As a side note, when I tried SSHing into my worker and controller nodes to debug, I got stuck when it asked me for a password. Could anyone tell me what these are for a kube-aws created instance?

**Comment by martindanko** [comment]
Hi @reiinakano - To diagnose, ssh into a machine and try mounting the volume according to the AWS instructions.

If you're unable to, it's sounds as though it may possibly be a security group issue, make sure the security group your minions (nodes) are in are associated with the EFS in the security group section in the EFS Console.

**Comment by reiinakano** [comment]
Hi @martindanko thanks for the reply. 

Actually, I figured it out when I read the comment on cluster.yaml that said it used nodePath to mount the EFS. I was just wondering why this works and mounting it as a Persistentvolume does not. 

Anyway, another thing Im trying to figure out is why is there a password when I try to access my EC2 instances using my key pair. Never read anything in the docs about this. Would appreciate if you could help with that :) anyway, closing this issue since my original issue is resolved

**Comment by martindanko** [comment]
The later problem is probably due to two things, either you're using the incorrect username. CoreOS uses the username "core" e.g. core@123.123.123.123 or you've not loaded your key properly in ssh.

Test using **ssh-add -l** that a lowercase L for list I believe.

**Comment by reiinakano** [comment]
Wow, okay I feel really dumb. I was using the default "ec2-user" username from Amazon Linux instances. Thanks so much @martindanko !!

**Comment by martindanko** [comment]
You're welcome. Glad to have helped.
