### ISSUE TITLE
Dropping deprecated `hostedZone`(not `hostedZoneId`) in cluster.yaml

### ISSUE THREAD

**Issue by mumoshu** [coreos/kube-aws#287]
As the subject says.
Although there's no fixed number of releases until a deprecated feature/configuration key is dropped yet, I guess no one is using the deprecated key now and the deprecation was represented in a comment in the `cluster.yaml` for enough period.

**Comment by icereval** [comment]
please do, conflicts with the `hostedZone` struct 👍

**Comment by cmcconnell1** [comment]
Yes, please remove deprecated / commented out code.  Thanks
