### ISSUE TITLE
Proposal: AWS environment variable file

### ISSUE THREAD

**Issue by pieterlange** [coreos/kube-aws#29]
It is currently impossible to directly utilize cloudformation Refs inside of the userdata / `cloud-init` files as those files get passed verbatim to the `UserData` parameters in the `stack-template.json` file.

I think it's useful to provide an `/etc/aws-environment` file in which to pass a list of AWS environment variables by `Ref`, for the end user to utilize using systemd's `EnvironmentFile` [option ](https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html).

We can easily append this right now by using ``Fn::Join`` to the UserData as the last section in `cloud_init` is `write_files`.

Immediate usecase: passing in cloudformation [wait condition urls](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-waitcondition.html).

**Comment by camilb** [comment]
This will work even if the UserData it's gzip compressed?  

I was looking to use this for `etcd-aws`.
In crewjam's cloudformation template is set like this, but it is not compressed. 

    "UserData": {
      "Fn::Base64": {
        "Fn::Join": [
          "",
          [
            "#cloud-config\n\nwrite_files:\n  - path: \"/etc/etcd_aws.env\"\n    permissions: \"0444\"\n    owner: \"root\"\n    content: \"ETCD_BACKUP_BUCKET=",
            {
              "Ref": "BackupBucket"
            },
            "\"\ncoreos:\n  units:\n    - name: etcd-aws.service\n      command: start\n      enable: true\n      content: |\n        [Unit]\n        Description=configures and runs etcd in AWS.\n        \n        [Install]\n        WantedBy=multi-user.target\n        \n        [Service]\n        Restart=always\n        EnvironmentFile=/etc/etcd_aws.env\n        ExecStart=/usr/bin/docker run --name etcd-aws \\\n          -p 2379:2379 -p 2380:2380 \\\n          -v /var/lib/etcd2:/var/lib/etcd2 \\\n          -e ETCD_BACKUP_BUCKET -e ETCD_BACKUP_KEY \\\n          --rm crewjam/etcd-aws\n        ExecStop=-/usr/bin/docker rm -f etcd-aws\n        \n    - name: cfn-signal.service\n      command: start\n      enable: true\n      content: |\n        [Unit]\n        Description=Cloudformation Signal Ready\n        After=etcd-aws.service\n        Requires=etcd-aws.service\n        \n        [Install]\n        WantedBy=multi-user.target\n        \n        [Service]\n        Type=oneshot\n        EnvironmentFile=/etc/environment\n        ExecStart=/bin/bash -c '\\\n        set -ex; \\\n        eval $(docker run crewjam/ec2cluster); \\\n        docker run --rm crewjam/awscli cfn-signal \\\n          --resource MasterAutoscale --stack $TAG_AWS_CLOUDFORMATION_STACK_ID \\\n          --region $REGION || true; \\\n        '\n        \n"
          ]
        ]
      }
    }
    }
    },

**Comment by pieterlange** [comment]
Ah, i didn't check if the userdata was compressed. We could switch it to uncompressed if we detect a seting in `cluster.yaml`, eg:

```yaml
awsEnvironmentFile: |
  WAITHANDLE='{ "Ref" : "myWaitHandle" }'
  EFSID='{ "Ref": "ElasticFileSystem" }'
```
