### ISSUE TITLE
Missing git history from coreos-kubernetes/tree/master/multi-node/aws

### ISSUE THREAD

**Issue by kenden** [coreos/kube-aws#3]
The first commit message in this repo says:
"Move everything under the multi-node/aws directory from coreos/coreos-kubernetes c25ac21"

But all the commit history from the original location is lost
https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/aws

Could you maybe extract the directory's history?
http://stackoverflow.com/questions/1662753/export-subtree-in-git-with-history

Also, should https://github.com/coreos/coreos-kubernetes/tree/master/multi-node/aws be stopped/blocked if this repo is to become the official location?

**Comment by mumoshu** [comment]
Hi @kenden 
Thanks for your feedback!

I've just finished recovering the history with the procedure you've provided.

It does seem to work but a gotcha(at least for me) is that, even though it doesn't relate to the procedure, each directory's history doesn't survive `git mv` so e.g. looking into `config/`'s history, you'll see that the origin of it is now my `git mv` commit https://github.com/coreos/kube-aws/commits/master/config
However, the root directory's history is preserved as we might have expected https://github.com/coreos/kube-aws/commits/master so I assume it is still very useful.

Are you satisfied to the result? 
Further comments and feedbacks are welcome!

Also, regarding the former repo, would you please wait until coreos guys make an announcement?

**Comment by kenden** [comment]
Much nicer thanks @mumoshu!
Note it's still possible to get the history of file under config with for ex:`git log --follow config.go`.
Cheers!

**Comment by mumoshu** [comment]
@kenden I wasn't aware of it but `--follow` did work. Thanks for the tip!

**Comment by mumoshu** [comment]
@kenden FYI regarding the former repo, https://github.com/coreos/coreos-kubernetes/pull/751 is WIP

**Comment by mumoshu** [comment]
I guess you've probably noticed that the move from the coreos-kubernetes to the kube-aws repo is announced multiple times in github issues. There's also a notice in the very beginning of the README 👍 

I'm closing this as the original issues are resolved but feel free to reopen if necessary.
Thanks for your interest and feedback, @kenden!
