### ISSUE TITLE
v0.9.4-rc.2: CloudFormation Stack syntax error: ValidationError: Template format error: Output InstanceEtcd0PrivateDnsName is malformed.

### ISSUE THREAD

**Issue by duanshiqiang** [coreos/kube-aws#308]
The stack template generated outputs Etcd instance private DNS name which contains invalid name assigned to them. The section inside `stack-template.json` is:

```
{{range $index, $_ := $.EtcdInstances}}
{{if $index}},{{end}}"InstanceEtcd{{$index}}PrivateDnsName": {
  "Description": "The resolvable hostname of etcd node {{$index}}",
  "Value": { "Fn::GetAtt" : [ "InstanceEtcd{{$index}}", "PrivateDnsName" ] },
  "Export": { "Name" : "{{$.ClusterName}}-InstanceEtcd{{$index}}PrivateDnsName" }
}
{{end}}
```

After rendered the stack from `cluster.yaml`, when doing `kube-aws validate` it gives below error:

```
Error: invalid cloudformation stack: ValidationError: Template format error: Output InstanceEtcd0PrivateDnsName is malformed. The Name field of every Export member must be specified and consist only of alphanumeric characters, colons, or hyphens.
```

It seems AWS CloudFormation doesn't allow `Export` name contains digits, it only allows alphanumeric characters, colons, or hyphens.

I guess the name should be modified to remove the index but I guess the intention to put the index is to output all the private DNS names for Etcd instances. For that, maybe output one value as a single string with DNS names separated by comma would give similar result. Users/other stacks who consume this output can use CloudFormation intrinsic function `Fn::Split` to get a list of individual values.

**Comment by redbaron** [comment]
How does this section look like when you do `kube-aws up --export --pretty-prtint` ?

**Comment by duanshiqiang** [comment]
I deleted my cluster.yaml and I found that I can't reproduce this error.. I guess something wrong in my side instead of kube-aws. If you guys can't reproduce also I think this issue should be closed.
