### ISSUE TITLE
Using experimental.auditLog to stdout lead to 16GB docker log file and errors

### ISSUE THREAD

**Issue by whereisaaron** [coreos/kube-aws#322]
I have been trying enabling the audit log to stdout with the following `cluster.yaml` settings.
```
experimental:
  auditLog:
    enabled: true
    maxage: 30
    logpath: /dev/stdout
```

After a few days, the kube-apiserver log began to fill with write errors after out of space. (This seems strange up front, how come there was space for the error to log that it couldn't log?)
```
E0214 18:32:28.250100       1 audit.go:126] Unable to write audit log: 2017-02-14T18:32:28.250063114Z AUDIT: id="6a9fd429-c827-4215-95b4-d7cf2f8cf3a4" ip="172.23.146.164" method="GET" user="kube-worker" as="<self>" asgroups="<lookup>" namespace="<none>" uri="/api/v1/nodes?fieldSelector=metadata.name%3Dip-172-31-148-171.ap-southeast-2.compute.internal&resourceVersion=0"
E0214 18:32:28.250524       1 audit.go:46] Unable to write audit log: 2017-02-14T18:32:28.2505111Z AUDIT: id="6a9fd429-c827-4215-95b4-d7cf2f8cf3a4" response="200"
```

There was 7.5GB free on the root filesystem but I noted the docker log file for kube-apiserver had grown to 16GB. This too was surprising as I understood that docker logs on Kubernetes are rotated at maximum 10MB?
```
-rw-r-----. 1 root root  16G Feb 14 18:43 kube-apiserver-ip-172-31-146-7.ap-southeast-2.compute.internal_kube-system_kube-apiserver-2cfd7f96cab408772caafb422101a5232379583dad9e7c4fea8c42234ef44d07.log
```

I removed the 'auditlog' setting from kube-apiserver and upon restart there are no write errors and a small log.

**Comment by redbaron** [comment]
Before https://github.com/coreos/kube-aws/issues/134 is solved, you can apply solution proposed in a first commit. Or better make a PR :)

**Comment by whereisaaron** [comment]
Oh dear, oh dear, oh dear. Not a malfunction, there just isn't any log rotation enabled at all! Thanks for the heads-up @redbaron. I'll close this issue, as it isn't adding anything #134 isn't covering.
