### ISSUE TITLE
kube-aws render credentials using publicly purchased ssl certificate?

### ISSUE THREAD

**Issue by simoami** [coreos/kube-aws#330]
Is it possible and relevant to use a publicly issued SSL certificate for `api.domain.com` to generate kube credentials? 

I currently have the following from godaddy:
- gd_bundle-g2-g1.crt
- 2c179c1e4e2bb02d.crt
- public.pem (generated from above 2 crts)
- private.pem

Note: The custom domain `api.domain.com` is already setup to access the api gateway via https.

**Comment by redbaron** [comment]
kube-aws setup not only validates server certs, but also validates a client cert. for that to work, godaddy would need to sign your client certs too. not sure if they provide such a service.

You can also use godaddy cert from api server and self-generated ones for client, just put all CA certs (both goddady bundle and local CA chain you used to sign certs) into ca.crt file

**Comment by pieterlange** [comment]
I didn't know that was possible!

That doesn't win you anything though, in fact only grows your exposure; now you're dependent on your own management of a CA and any (mistakenly) client certificates by godaddy (..) end up impacting your cluster as well.

**Comment by simoami** [comment]
I approached this the wrong way. The public ssl was meant for an app level front-end service, which I ended up using on a service.yaml. As for the cluster, a private ca and generated certs is ok because it's for admin and internal access anyways.
