### ISSUE TITLE
Is `workerSecurityGroupIds` no longer supported?

### ISSUE THREAD

**Issue by c-knowles** [coreos/kube-aws#333]
I had a backlog item to start using this new feature but it seems it's no longer in the latest RC but is still inside the cluster.yaml template.

https://github.com/coreos/kube-aws/pull/127 added this feature and in [this commit](https://github.com/coreos/kube-aws/commit/aeb122dcccd2a4ec69712da2333ced02047bd1c1#diff-bfeae88573cf9afa7638e19a4f7b4535) it seems to get removed/changed (search for `workerSecurityGroupIds`). I'm not sure if the test is entire gone or now we are expecting `worker.nodePools[].loadBalancer.securityGroupIds`?

**Comment by c-knowles** [comment]
I guess if this did change to be under `loadBalancer` then the name is a bit confusing if it's used for the purpose of the original issue https://github.com/coreos/kube-aws/issues/43.

**Comment by mumoshu** [comment]
@c-knowles Thanks as always for your feedback.
I've never intended to drop `workerSecurityGroupIds`!
If it worked correctly, it should have concatenated workerSecurityGroupIds with loadBalancer.securityGroupIds to finally render all the additional security groups associated to nodes.

**Comment by c-knowles** [comment]
I found `worker.nodePools[].loadBalancer.securityGroupIds` works as expected so I am able to add SGs to worker node pools, however I couldn't get `workerSecurityGroupIds` to work. My vote goes for any fixes to this to just add `worker.nodePools[].securityGroupIds` or `worker.securityGroupIds` as the base set of SGs.

**Comment by mumoshu** [comment]
@c-knowles Could you try `worker.securityGroupIds`? I'd been forgetting that I experimentally renamed it in #315 for consistency reason.

However, I believe it's true that I've (mistakenly) dropped the support for the former `workerSecurityGroupIds`.
Would you like to support not only the new `worker.securityGroupIds` but also the former `workerSecurityGroupIds`?

**Comment by c-knowles** [comment]
@mumoshu not bothered at all about the old name, I think it's better to update cluster.yaml than keep supporting so many similar options. I will try and if it works we just need to update cluster.yaml template.

**Comment by mumoshu** [comment]
Thanks @c-knowles!
Did `worker.securityGroupIds` work for you?

**Comment by c-knowles** [comment]
Just run through these options, I can confirm the following with v0.9.4:
* `workerSecurityGroupIds[]` does not work as above
* `worker.nodePools[].loadBalancer.securityGroupIds[]` works as above assuming the `loadBalancer` section is `enabled: true`
* `worker.securityGroupIds[]` does not work
* `worker.nodePools[].securityGroupIds[]` works

**Comment by mumoshu** [comment]
@c-knowles Ah, sorry! Yes, as you've observed, it should be `worker.nodePools[].securityGroupIds`.

**Comment by mumoshu** [comment]
Closing this as fixed via #382. Thanks for your contribution @c-knowles
