### ISSUE TITLE
Run cluster in HA (multi-az)

### ISSUE THREAD

**Issue by simoami** [coreos/kube-aws#336]
Apologies if i might have missed this, but Is it possible to configure kube-aws to spread workers across multiple availability zone? e.g. us-east-1a, us-east-1b ...etc.

Ref. https://kubernetes.io/docs/admin/multiple-zones/

**Comment by redbaron** [comment]
look at cluster.yaml comments

**Comment by simoami** [comment]
oh, I see the relevant docs here: 
https://github.com/coreos/kube-aws/blob/master/Documentation/kubernetes-on-aws-node-pool.md#deploying-a-multi-az-cluster-with-cluster-autoscaler-support-with-node-pools
