### ISSUE TITLE
Custom settings not available in node pools 

### ISSUE THREAD

**Issue by ankon** [coreos/kube-aws#346]
I'm seeing this error for a template rendered with 0.9.4-rc.3, and a node pool with a change that requires the custom settings:
~~~~
Error: Failed to initialize cluster driver: failed to load node pool #0: failed to render worker cloud config: template: userdata/cloud-config-worker:389:65: executing "userdata/cloud-config-worker" at <.CustomSettings.work...>: can't evaluate field CustomSettings in type *config.ComputedConfig
~~~~

Change in the user data:
```diff
    - name: swap.service
      command: start
      content: |
        [Unit]
        Description=Turn on swap
        [Service]
        Type=oneshot
        Environment="SWAP_PATH=/var/vm" "SWAP_FILE=swapfile1"
        ExecStartPre=-/usr/bin/rm -rf ${SWAP_PATH}
        ExecStartPre=/usr/bin/mkdir -p ${SWAP_PATH}
        ExecStartPre=/usr/bin/touch ${SWAP_PATH}/${SWAP_FILE}
        ExecStartPre=/bin/bash -c "fallocate -l {{.CustomSettings.workerSwapSize}} ${SWAP_PATH}/${SWAP_FILE}"
        ExecStartPre=/usr/bin/chmod 600 ${SWAP_PATH}/${SWAP_FILE}
        ExecStartPre=/usr/sbin/mkswap ${SWAP_PATH}/${SWAP_FILE}
        ExecStartPre=/usr/sbin/sysctl vm.swappiness=10
        ExecStart=/sbin/swapon ${SWAP_PATH}/${SWAP_FILE}
        ExecStop=/sbin/swapoff ${SWAP_PATH}/${SWAP_FILE}
        ExecStopPost=-/usr/bin/rm -rf ${SWAP_PATH}
        RemainAfterExit=true
        [Install]
        WantedBy=multi-user.target
```

**Comment by redbaron** [comment]
not to say that `.CustomSettings` shouldn't be fixed, but why do you need swap? there is even a flag to enable startup with swap, but description suggests, that starting from version 1.6 kubelet going to refuse to start if it detects that swap is enabled:

>      --experimental-fail-swap-on                               Makes the Kubelet fail to start if swap is enabled on the node. This is a temporary option to maintain legacy behavior, failing due to swap enabled will happen by default in v1.6.

**Comment by ankon** [comment]
Interesting. Didn't know that, so that's certainly to be considered. 

Why do I _need_ swap: I'm not 100% sure I do, but given the apps I'm running in the cluster I know that they might have quite a bit of "unused" memory (Java ...).

**Comment by redbaron** [comment]
`resources.request.memory` is used to schedule, but doesn't limit resource usage. so it can be set smaller than actual usage, which itself is limited by `resources.limit.memory`.

Actually Java memory is one of the most predictable. from previous experience it was safe to set container limit to Heap size (defined by `-Xmx`) + 256 MB
