### ISSUE TITLE
kube-aws validate  stack.json does not exist.

### ISSUE THREAD

**Issue by yawboateng** [coreos/kube-aws#379]
running v0.9.5-rc.1

kube-aws validate --s3-uri s3://buketName throws an error 

Error: failed to validate node pool #0: invalid cloudformation stack: ValidationError: Template file referenced by https://s3.amazonaws.com/buketName/kube-aws/clusters/ENV-NAME/exported/stacks//stack.json does not exist

seems there  is an extra "/" before stack.json

**Comment by yawboateng** [comment]
getting this same error for version above v0.9.3

**Comment by mumoshu** [comment]
Hi @yawboateng, thanks for trying kube-aws!
I've replied to you in https://github.com/coreos/kube-aws/issues/378#issuecomment-284281979

**Comment by yawboateng** [comment]
Thanks, working now

**Comment by mumoshu** [comment]
Glad to hear it worked for you!
I'd appreciate it if you could submit another issue(s) if you find any to improve kube-aws.
