### ISSUE TITLE
etcdDataVolumeEncrypted not creating encrypted volumes

### ISSUE THREAD

**Issue by swestcott** [coreos/kube-aws#383]
I've set `etcdDataVolumeEncrypted: true` in my `cluster.yaml` file however the resulting volumes are marked as `Encrypted: Not Encrypted` in the AWS console.

From a initial look, I wonder if 341323e0879f3e30170fe1ebc0ddd6f653245d26 inadvertently removed the conditional logic around `EtcdDataVolumeEncrypted` in `stack-template.json`?

**Comment by swestcott** [comment]
A potential secondary issue, after re-adding `EtcdDataVolumeEncrypted`, it seems that the EBS volumes are encrypted with the default `aws/ebs` key rather than the `kms-key-arn` passed in to `kube-aws init`.

**Comment by mumoshu** [comment]
@swestcott Thanks for the feedbacks 👍 

> From a initial look, I wonder if 341323e0879f3e30170fe1ebc0ddd6f653245d26 inadvertently removed the conditional logic around `EtcdDataVolumeEncrypted` in `stack-template.json`?

It certainly seems so 😢 

> it seems that the EBS volumes are encrypted with the default `aws/ebs` key rather than the `kms-key-arn` passed in to `kube-aws init`.

Good catch. Does it make sense to always use the kms key specified via `kmsKeyArn` for encrypting EBS volumes, or would you like an another configuration key like `etcdDataVolumeEncryptionKmsKeyArn`(very long 😄) for flexibility?

**Comment by mumoshu** [comment]
@swestcott `etcdDataVolumeEncrypted` is fixed in #387 and included in v0.9.5-rc.2.
Could you confirm that it is now working?

**Comment by mumoshu** [comment]
I'll keep this open until the second question in https://github.com/coreos/kube-aws/issues/383#issuecomment-284563722 is answered.

**Comment by swestcott** [comment]
@mumoshu Reusing the existing `kmsKeyArn` value suites me. The core point for me is a kube-aws doesn't share it's key with anything else.

**Comment by swestcott** [comment]
I've confirmed `EtcdDataVolumeEncrypted` is working on `master`

**Comment by mumoshu** [comment]
Thanks for the confirmation @swestcott!
I'm closing this as fixed but please feel free to reopen if necessary.
Btw I've opened an another issue #393 for your feature request.
Let's keep discussing there.
