### ISSUE TITLE
`kube-aws caculator` does not recognize `t2.xlarge` type

### ISSUE THREAD

**Issue by andromedarabbit** [coreos/kube-aws#388]
> Error: failed to estimate cost for node pool #0 ValidationError: t2.xlarge is an invalid InstanceType value. Valid values are [c1.medium, c1.xlarge, c3.2xlarge, c3.4xlarge, c3.8xlarge, c3.large, c3.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c4.large, c4.xlarge, cc1.4xlarge, cc2.8xlarge, cg1.4xlarge, cr1.8xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge, d2.xlarge, g2.2xlarge, g2.8xlarge, hi1.4xlarge, hs1.8xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge, i2.xlarge, m1.large, m1.medium, m1.small, m1.xlarge, m2.2xlarge, m2.4xlarge, m2.xlarge, m3.2xlarge, m3.large, m3.medium, m3.xlarge, m4.10xlarge, m4.2xlarge, m4.4xlarge, m4.large, m4.xlarge, r3.2xlarge, r3.4xlarge, r3.8xlarge, r3.large, r3.xlarge, t1.micro, t2.large, t2.medium, t2.micro, t2.small]

New instance type is not recognized

**Comment by mumoshu** [comment]
Thanks for the report @andromedarabbit!
@gianrubio Any chance you could look into this? Perhaps we'd need to upgrade our aws-sdk-go to catch up with latest instance types or is it just a cloudformation restriction?

**Comment by gianrubio** [comment]
Yes @mumoshu, I'll do that during this weekend

**Comment by gianrubio** [comment]
@mumoshu upgrading the aws-sdk-go fix this error

**Comment by andromedarabbit** [comment]
I appreciate that.
