### ISSUE TITLE
controller unable to reach etcd in us-east-1

### ISSUE THREAD

**Issue by BertHartm** [coreos/kube-aws#397]
First, thanks for this project, the documentation and output has been great for learning.

I'm attempting to spin up a cluster on us-east-1, and running into an issue where the controller box cannot reach the etcd box.

It appears that `/etc/etcd-environment` is getting set to a hostname of the form `ec2-xx-xx-xx-xx.us-east-1.compute.amazonaws.com` instead of the correct form for us-east of `ec2-xx-xx-xx-xx.compute-1.amazonaws.com`. It's picking up the right IP, just the wrong form for the FQDN.

I'll be looking for how that FQDN gets formed, but want to throw an issue up in case I'm missing something obvious or going the wrong direction.

**Comment by mumoshu** [comment]
@BertHartm Thanks for trying kube-aws and the detailed feedback 👍 
kube-aws as of today relying on [these funcs](https://github.com/coreos/kube-aws/blob/master/model/region.go#L23-L32) to pick up correct private and public FQDNs of EC2 instances for a specified region.
The one for public FQDNs, the func `PublicDomainName`, does seem to be missing a condition to treat us-east-1 specifically, so it does seem to be the cause of your problem.

**Comment by mumoshu** [comment]
The func has been there since v0.9.5-rc.1 so is the bug.
I'll try to fix it asap but if you can do it earlier than me, I'd appreciate it 👍

**Comment by mumoshu** [comment]
I've submitted the PR #398 to fix this.
I'm running E2E tests in us-east-1 and it seems to be working so far.

**Comment by mumoshu** [comment]
I've released v0.9.5-rc.3 which includes the fix for this!
Please reopen if the problem still persists.
