### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by swestcott** [coreos/kube-aws#403]
I couldn't see a license agreement anywhere, what license is kube-aws release under?

**Comment by swestcott** [comment]
Apologies, it's in `CONTRIBUTING.md`...

**Comment by pierreozoux** [comment]
Could you reopen this and move it to `LICENSE` file, then there is a nice logo on the top right corner, like here: https://github.com/apprenda/kismatic?

Thanks!

**Comment by mumoshu** [comment]
Done 👍
