### ISSUE TITLE
What happened to signed releases?

### ISSUE THREAD

**Issue by nicr9** [coreos/kube-aws#63]
Hey everybody,

Are there any plans to sign future releases of `kube-aws`?

When this project was a part of coreos/coreos-kubernetes, a signature was provided with each release and you had the option of verifying it before untarring/installing. There still seems to be some vestigial documentation explaining how to go about verifying releases in the [README.md](https://github.com/coreos/kube-aws#download-pre-built-binary).

Does who/whatever creates the releases not have access to CoreOS's signing key? Should we clear out the aforementioned parts of the docs?

**Comment by pieterlange** [comment]
Future full releases will be signed! @colhom @mumoshu can probably chip in here on details.

**Comment by mumoshu** [comment]
Hi @nicr9, sorry for the confusion about that.

As you've imagined, I don't have the access to signing key but @colhom is.
Currently, we're going to sign only non-rc, final releases.

How would you like the docs to be written about this?
Would inserting `Currently, only binaries coming from the final release for each version is signed.` to the first line in https://github.com/coreos/kube-aws#download-pre-built-binary suffice?

**Comment by colhom** [comment]
Hi everyone- we'll have v0.9.0 signed/fully released for you by the end of this week!

**Comment by nicr9** [comment]
@mumoshu I've opened #66 with some changes that I think should clarify things.

Thanks everyone!
