### ISSUE TITLE
UserData for the Controller and Worker

### ISSUE THREAD

**Issue by kenwan12** [coreos/kube-aws#70]
Hi,

   We are used to put some customised tasks into the AWS Cloud Init part for adding own logging and other stuff to AWS instances.

  I wonder if the userdata can be decrypted to allow us achieve it ?

  Base64 decode it and then followed by using the KMS key to decrypt ?

Thanks

Ken

**Comment by pieterlange** [comment]
You can add customized tasks to cloudinit by editting the files in the `userdata` directory after generating the cluster assets with `kube-aws render stack`.

**Comment by kenwan12** [comment]
I see. So I can edit the cloud-config-controller and cloud-config-worker under the userdata folder before I call the kube-aws up then.

Thanks

Ken
