### ISSUE TITLE
does hostPort not work on kube-aws/CoreOS?

### ISSUE THREAD

**Issue by rajivm** [coreos/kube-aws#91]
I am unable to get it to docker expose the port on the host. See https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-254918942 also

**Comment by pieterlange** [comment]
This is an issue in kubernetes. You can use `nodePort` as temporary workaround, which isn't ideal, but it's something..

**Comment by rajivm** [comment]
@pieterlange Appreciate the quick response. Yeah not ideal because more proxying/hopping. Any idea why this only affects CoreOS?

**Comment by pieterlange** [comment]
Why do you think it's just CoreOS?

If i remember correctly it's in the new CNI code and the CNI (in our case flannel) needs to implement it.

**Comment by camilb** [comment]
Had a problem with nginx ingress controller when using calico and solved using `hostNetwork: true`  in deployment. Maybe it works in this case also. 
Ex:

        spec:
          hostNetwork: true
          containers:
          - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
            name: nginx-ingress-lb

**Comment by pieterlange** [comment]
This is indeed the most common usecase for using `hostPort` and is not affected by the pod not getting its own pod IP :+1: nice workaround @camilb!

**Comment by mumoshu** [comment]
@rajivm Thanks for starting the discussion!
After reading the whole thread, I believe this is not a CoreOS/kube-aws issue but rather a upstream issue.

I'd like to decide how we handle this.
Should we just document this issue/restriction with companions like @pieterlange's comment about `nodePort` and @camilb 's comment about `nginx-ingress-controller` for now in our doc?

**Comment by mumoshu** [comment]
I'm closing this as it is now documented in #162 :bow:
